---
- name: Ensure Apache WebServer is installed
  apt:
    name: apache2

- name: Ensure is enabled
  apache2_module:
    state: present
    name: rewrite

- name: Restart Apache
  systemd:
    state: restarted
    daemon_reload: yes
    name: apache2

- name: Ensure directory for PrestaShop exists
  file:
    path: /var/www/html/prestashop
    state: directory