---
- name: Ensure PHP is installed
  apt:
    pkg:
      - libapache2-mod-php7.4
      - php7.4
      - php7.4-common
      - php7.4-curl
      - php7.4-gd
      - php7.4-imagick
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-json
      - php7.4-xsl
      - php7.4-intl
      - php7.4-zip