---
- include_tasks: RedHat-Setup.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: Debian-Setup.yml
  when: ansible_os_family == 'Debian'

- name: Download PrestaShop package
  get_url:
    url: "{{ prestashop_url }}"
    dest: /var/www/html/prestashop/prestashop_archive.zip

- name: Extract PrestaShop into /var/www/html/prestashop
  unarchive:
    src: /var/www/html/prestashop/prestashop_archive.zip
    dest: /var/www/html/prestashop
    remote_src: true

- name: Change privledges to prestashop directory for apache
  file:
    path: /var/www/html/prestashop
    state: directory
    recurse: true
    owner: www-data
    group: www-data