---
- name: Update apt repo and cache
  yum: 
    update_cache: true

- name: Upgrade all packages on servers
  yum: 
    name: "*"
    state: latest

- name: Ensure UnZip is installed
  yum:
    name: unzip
  state: present

- name: Ensure PHP is installed
  yum:
    name:
      - libapache2-mod-php7.4
      - php7.4
      - php7.4-common
      - php7.4-curl
      - php7.4-gd
      - php7.4-imagick
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-json
      - php7.4-xsl
      - php7.4-intl
      - php7.4-zip
    state: present

- name: Ensure Apache WebServer is installed
  yum:
    name: apache2
  state: present

- name: Ensure rewrite module for apache is enabled
  apache2_module:
    state: present
    name: rewrite

- name: Restart Apache
  service:
    name:  apache2
    state: restarted

- name: Ensure directory for PrestaShop exists
  file:
    path: /var/www/html/prestashop
    state: directory

- name: Ensure MySQL Server and Client are installed
  yum:
    name:
    - default-mysql-server
    - default-mysql-client
    state: present
  when: "{{ mysql_install == True}}"

- name: Ensure PyMySQL is installed
  yum: 
    name: python3-pymysql
    state: present

- name: Restart MySQL
  service:
    name: mysql
    state: restarted
  when: "{{ mysql_install == True}}"

- name: Ensure Database for PrestaShop is created
  mysql_db:
    name: "{{ mysql_prestashop_db }}"
    collation: utf8mb4_general_ci
    login_host: "{{ mysql_host }}"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_user_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Ensure user for PrestaShop database is created with privileges
  mysql_user:
    state: present
    name: "{{ mysql_prestashop_user }}"
    password: "{{ mysql_prestashop_password }}"
    priv: "{{ mysql_prestashop_db }}.*:ALL,GRANT"
    login_host: "{{ mysql_host }}"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_user_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock